name: Lint Specs

on:
  push:


jobs:
  ascynapi:
    runs-on: [ ubuntu-latest ]
    name: lint AsyncAPI
    strategy:
      matrix:
        file: [./light-switch-events-binary-mode.yaml, light-switch-events-structured-json.yaml]
    steps:
    - uses: actions/checkout@v4
    - name: Validate
      uses: asyncapi/github-action-for-cli@v3.1.1
      with:
        command: validate
        filepath: ${ matrix.file }
